#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Propishare.Resource", IsApplication=true)]

namespace Propishare
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int boton_1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int boton_2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Botones = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int fondo2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int fondo3 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int maco1b = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int maria = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int propishare = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int rayuela = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int Email = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int btnLogin = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int image = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int listView1 = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int textView2 = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int textView3 = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int textView4 = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int txtContraseñaMozo = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int MozoGestion = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MozoLogin = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Tema = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Theme_Custom = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
